version: '3'
services:
  Hive:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    depends_on: 
        - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "MyPassword001"
      ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"